### ISSUE TITLE
解决 less 1.5.1 处理 @import 的一个bug

### ISSUE THREAD

**Issue by leeight** [ecomfe/edp-build#22]
问题简化版是这样子的：

``` css
/** dep/esui/3.1.0-alpha.6/src/css/SearchBox.less */
.normal-search-icon() {
    background: transparent url(../img/search.png) no-repeat center -25px;
}
.active-search-icon() {
    background: transparent url(../img/search.png) no-repeat center 0;
}
.skin-search-button {
    .normal-search-icon();
    &:active {
        .active-search-icon();
    }
    &:hover {
        .active-search-icon();
    }
}
```

然后`dep/esui/3.1.0-alpha.6/src/css/main.less`引用了`SearchBox.less`，例如：

``` less
/** dep/esui/3.1.0-alpha.6/src/css/main.less*/
@import "./SearchBox.less";
```

最后`bug.less`引用了了`main.less`，也就是这样子的：

``` css
/** bug.less*/ 
@import "dep/esui/3.1.0-alpha.6/src/css/main.less";
```

此时执行`lessc -ru bug.less`，产出的代码是有问题的，如果直接执行`lessc -ru dep/esui/3.1.0-alpha.6/src/css/main.less`则是OK的。

目测问题是因为`.active-search-icon();`这个`mixin`被调用了两次，导致的问题
